services:
    mysql:
        container_name: db-f1sp
        environment:
            MYSQL_ROOT_PASSWORD: f1spf1rankAZU!
            MYSQL_ROOT_HOST: '%' # Allow root access from any host
            MYSQL_DATABASE: f1sp-db
            MYSQL_USER: f1sp
            MYSQL_PASSWORD: f1spf1rankAZU!
            MYSQL_ALLOW_EMPTY_PASSWORD: 'no' # Disallow empty passwords
        image: mysql:latest
        ports:
            - '3306:3306'
        restart: always
        volumes:
            - ./data:/var/lib/mysql
            - ./f1sp.sql:/docker-entrypoint-initdb.d/f1sp.sql
networks:
    default:
        name: f1sp-network
